export const IpcEventKeys = {
  AddWebOverlay: "add-web-overlay",
  GetWebOverlayList: "get-web-overlay-list",
  DeleteWebOverlay: "delete-web-overlay",
  EditWebOverlay: "edit-web-overlay",
  OpenWebOverlay: "open-web-overlay",
  CloseWebOverlay: "close-web-overlay",
  ReloadWebOverlay: "reload-web-overlay",
  UpdateIframePositionSize: "update-iframe-pos-size",
  InitWebOverlay: "init-web-overlay",
  ShowBorderWebOverlay: "show-border-web-overlay",
  IgnoreMouseEventWebOverlay: "ignore-mouse-event-web-overlay",
  EnableMoveWebOverlay: "enable-move-web-overlay",
  SetIframeUrlWebOverlay: "set-iframe-url-web-overlay",
  ShowPositionSizeSaveButton: "show-position-size-save-button",
  ImportOverlay: "import-overlay",
  ExportOverlay: "export-overlay",
  DeleteSettingHistory: "delete-setting-history",
};
